### ISSUE TITLE
Add to README.md and F-Droid Screenshots of Dark Theme

### ISSUE THREAD

**Issue by Korb** [thevindu-w/clip_share_client#17]
~~As you can see from the screenshots in README.md and on F-Droid, the app does not support dark theme. Please add it. Preferably in a black background version:~~

~~Google Android 14:~~

> ~~Dark Theme Screen / On some screens, Dark theme will use a solid black background which will help extend your battery life. After scheduling, Dark theme will be enabled when your screen is off.~~

~~F-Droid:~~

> ~~Use pure black background in dark theme. Recommended only for OLED screens.~~

~~[Catima](https://github.com/Hypfer/Catima):~~

> ~~Pure black background for dark theme (reduces battery usage on OLED displays).~~

**Comment by thevindu-w** [comment]
Did you mean a separate settings option to select dark mode? Currently ClipShare gets the system color. When the phone is in night mode, it will use that theme.
<img src="https://github.com/user-attachments/assets/703ecce5-ab1c-4d9a-a617-f904d220fcb3" alt="night_mode" height="500"/>
Does the Google, F-Droid and other recommendations require something additional to this?

**Comment by Korb** [comment]
Then I guess I should change the first post to "add to README.md and F-Droid screenshots of dark theme"?

**Comment by thevindu-w** [comment]
Ok, that's a good idea. I'll add the screenshots.
